#!/usr/bin/env bash
# This script lists files in the current directory, showing only the part
# of the name after the first dash (-)
for file in *
do
    if [ "$file" != "." ] && [ "$file" != ".." ]
    then
        echo "$file" | cut -d'-' -f2-
    fi
done
